name: React CI

on:
  push:
    branches:
      - master
    paths:
        - 'front/react/**'
        - '.github/workflows/ci_react.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'front/react/**'
      - '.github/workflows/ci_react.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'

    - name: Install dependencies
      working-directory: ./front/react
      run: npm install

    - name: Run build
      working-directory: ./front/react
      run: npm run build