name: CI Spring Main App

on:
  push:
    branches-ignore:
      - 'release/v[0-9]+.[0-9]+'
    paths:
      - 'back/spring/**'
  pull_request:
    branches-ignore:
      - 'release/v[0-9]+.[0-9]+'
    paths:
      - 'back/spring/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: ./back/spring
      run: mvn -B package --file pom.xml -DskipTests